### ISSUE TITLE
Reverse chronological view

### ISSUE THREAD

**Issue by Phantop** [syeopite/priviblur#97] opened 2024-09-19 04:26 UTC
A reverse chronological view (in this case, oldest first) could be very useful, especially for viewing specific tags for a given user, as those that use Tumblr for comics tend to tag them. The current view has the awkward experience of:
- Pressing next until reaching the furthest point back in history
- Viewing pages from bottom to top, often scrolling up and down as longer posts aren't visible in one shot

Fixing either of these issues could be a huge improvement, though I do think the easiest change could be offering a button to reorder any given page from oldest to newest, regardless of changes to pagination (as I'm unsure how well Tumblr enables this).

**Comment by syeopite** [comment] 2024-09-19 04:50
Duplicate of #41

----

The button to reorder content on a single page from the last one to the first is definitely the most straight-forward way to implement this.

Since unfortunately Tumblr's current unofficial undocumented API does not provide any way to fetch posts from within a blog in chronological order that I'm aware of.

I think it might get easier once we add support for archive pages though, as then you can navigate by month instead of page by page.

**Closed** 2024-09-19 04:50 UTC
